<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Sway.Extras.Material3.Media</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sway.Extras.Material3\Sway.Extras.Material3.csproj" />
    <ProjectReference Include="..\Sway.Media\Sway.Media.csproj" />
  </ItemGroup>

</Project>
