// Regenerates Icons.Filled.cs, Icons.Outlined.cs, Icons.Round.cs, Icons.Sharp.cs and Icons.TwoTone.cs from Google's Material icon set (Apache 2.0).
//   npm i @material-design-icons/svg   (in any scratch folder)
//   node generate-icons.mjs <path to node_modules/@material-design-icons/svg> <output dir>
// Multi-shape icons are merged into one path; circles and ellipses become arcs. If any shape uses
// fill-rule="evenodd" the whole icon is flagged EvenOdd. Faint (opacity < .5) shapes of two-tone icons
// become the Secondary path.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const [src, out] = process.argv.slice(2);
if (!src || !out) throw new Error('usage: node generate-icons.mjs <svg package dir> <output dir>');

const pascal = n => {
  const s = n.split('_').map(p => p[0].toUpperCase() + p.slice(1)).join('');
  return /^[0-9]/.test(s) ? '_' + s : s;
};
const num = v => String(+v.toFixed(4));
const attr = (tag, name) => new RegExp(`[ ]${name}="([^"]*)"`).exec(tag)?.[1];

function toPath(svg) {
  const main = [], faint = [];
  const evenOdd = /fill-rule="evenodd"/.test(svg);
  for (const m of svg.matchAll(/<(path|circle|ellipse)\b[^>]*>/g)) {
    const [tag, kind] = m;
    if (attr(tag, 'fill') === 'none') continue;
    // Two-tone icons draw their lighter layer at 30% opacity.
    const list = +(attr(tag, 'opacity') ?? attr(tag, 'fill-opacity') ?? 1) < 0.5 ? faint : main;
    if (kind === 'path') list.push((list.length ? 'M0 0' : '') + attr(tag, 'd')); // reset the pen so a leading relative m stays absolute
    else {
      const cx = +attr(tag, 'cx'), cy = +attr(tag, 'cy');
      const rx = +(attr(tag, 'rx') ?? attr(tag, 'r')), ry = +(attr(tag, 'ry') ?? attr(tag, 'r'));
      list.push(`M${num(cx - rx)} ${num(cy)}a${num(rx)} ${num(ry)} 0 1 0 ${num(2 * rx)} 0a${num(rx)} ${num(ry)} 0 1 0 ${num(-2 * rx)} 0z`);
    }
  }
  return { d: main.join(''), secondary: faint.join(''), evenOdd };
}

const RESERVED = ['Icons', 'Outlined', 'Round', 'Sharp', 'TwoTone', 'Equals', 'ToString', 'GetType', 'GetHashCode', 'ReferenceEquals'];

function generate(style, indent) {
  const dir = join(src, style);
  const names = readdirSync(dir).filter(f => f.endsWith('.svg')).map(f => f.slice(0, -4)).sort();
  const seen = new Set();
  const pad = ' '.repeat(indent);
  let body = '';
  for (const n of names) {
    const id = pascal(n);
    if (seen.has(id) || RESERVED.includes(id)) throw new Error(`name clash: ${n} -> ${id}`);
    seen.add(id);
    const { d, secondary, evenOdd } = toPath(readFileSync(join(dir, n + '.svg'), 'utf8'));
    const extra = (evenOdd ? ', EvenOdd: true' : '') + (secondary ? `, Secondary: "${secondary}"` : '');
    body += `${pad}public static IconData ${id} => new("${d}"${extra});\n`;
  }
  return { body, count: names.length };
}

const header = '// <auto-generated>Material icons (Apache 2.0, Google). Regenerate with tools/generate-icons.mjs.</auto-generated>\nnamespace Sway.Widgets;\n\npublic static partial class Icons\n{\n';
const counts = [];
const filled = generate('filled', 4);
writeFileSync(join(out, 'Icons.Filled.cs'), header + filled.body + '}\n');
counts.push(`filled ${filled.count}`);
for (const [style, cls, doc] of [['outlined', 'Outlined', 'outlined'], ['round', 'Round', 'rounded'], ['sharp', 'Sharp', 'sharp-cornered'], ['two-tone', 'TwoTone', 'two-tone']]) {
  const g = generate(style, 8);
  writeFileSync(join(out, `Icons.${cls}.cs`), header + `    /// <summary>The ${doc} variants of the Material icons.</summary>\n    public static class ${cls}\n    {\n` + g.body + '    }\n}\n');
  counts.push(`${style} ${g.count}`);
}
console.log(counts.join(', '));
