<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-android</TargetFramework>
    <SupportedOSPlatformVersion>26</SupportedOSPlatformVersion>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationId>com.sway.example</ApplicationId>
    <ApplicationTitle>Sway Example</ApplicationTitle>
    <ApplicationVersion>1</ApplicationVersion>
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sway.Example\Sway.Example.csproj" />
    <ProjectReference Include="..\Sway.Platform.Android\Sway.Platform.Android.csproj" />
  </ItemGroup>

</Project>
