<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Sway.Extras.Shopify</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Fonts\*.ttf" LogicalName="Sway.Extras.Shopify.Fonts.%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sway.Widgets\Sway.Widgets.csproj" />
  </ItemGroup>

</Project>
