<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sway.Example\Sway.Example.csproj" />
    <ProjectReference Include="..\Sway.Platform.Headless\Sway.Platform.Headless.csproj" />
  </ItemGroup>

</Project>
