using SkiaSharp;

namespace Sway.Widgets;

/// <summary>
/// CSS-grid-style layout: explicit column and row tracks (px, fr, auto), gaps, item spans, explicit or automatic
/// (row-major, sparse) placement, and per-item alignment.
/// </summary>
public sealed class RenderGrid : RenderBoxContainer
{
    IReadOnlyList<GridTrack> _columns, _rows;
    GridTrack _autoRow;
    float _columnGap, _rowGap, _autoFillMin;

    public RenderGrid(IReadOnlyList<GridTrack> columns, IReadOnlyList<GridTrack> rows, GridTrack autoRow, float columnGap, float rowGap, float autoFillMin)
    {
        _columns = columns; _rows = rows; _autoRow = autoRow; _columnGap = columnGap; _rowGap = rowGap; _autoFillMin = autoFillMin;
    }

    public void Update(IReadOnlyList<GridTrack> columns, IReadOnlyList<GridTrack> rows, GridTrack autoRow, float columnGap, float rowGap, float autoFillMin)
    {
        _columns = columns; _rows = rows; _autoRow = autoRow; _columnGap = columnGap; _rowGap = rowGap; _autoFillMin = autoFillMin;
        MarkNeedsLayout();
    }

    protected override void SetupParentData(RenderObject child)
    {
        if (child.ParentData is not GridParentData) child.ParentData = new GridParentData();
    }

    static GridParentData PD(RenderBox c) => (GridParentData)c.ParentData!;

    protected override void PerformLayout()
    {
        float maxW = Constraints.MaxWidth, maxH = Constraints.MaxHeight;

        // --- tracks: columns may be generated by auto-fill ---
        var cols = _columns.ToList();
        if (_autoFillMin > 0 && float.IsFinite(maxW))
        {
            int n = Math.Max(1, (int)MathF.Floor((maxW + _columnGap) / (_autoFillMin + _columnGap)));
            cols = Enumerable.Repeat(GridTrack.Fr(1), n).ToList();
        }
        if (cols.Count == 0) cols.Add(GridTrack.Fr(1));

        // --- placement ---
        var occupied = new List<bool[]>();
        bool[] RowOcc(int r) { while (occupied.Count <= r) occupied.Add(new bool[cols.Count]); return occupied[r]; }
        bool Fits(int r, int c, int rs, int cs)
        {
            if (c + cs > cols.Count) return false;
            for (int i = r; i < r + rs; i++) for (int j = c; j < c + cs; j++) if (RowOcc(i)[j]) return false;
            return true;
        }
        void Mark(int r, int c, int rs, int cs) { for (int i = r; i < r + rs; i++) for (int j = c; j < c + cs; j++) RowOcc(i)[j] = true; }

        foreach (var child in Children)
        {
            var pd = PD(child);
            pd.ColumnSpan = Math.Clamp(pd.ColumnSpan, 1, cols.Count);
            pd.RowSpan = Math.Max(1, pd.RowSpan);
            if (pd.Column is { } col && pd.Row is { } row)
            {
                pd.C = Math.Clamp(col, 0, cols.Count - pd.ColumnSpan); pd.R = Math.Max(0, row);
                Mark(pd.R, pd.C, pd.RowSpan, pd.ColumnSpan);
            }
            else pd.R = -1;
        }

        int curR = 0, curC = 0;
        foreach (var child in Children)
        {
            var pd = PD(child);
            if (pd.R >= 0) continue;
            if (pd.Column is { } fixedCol)
            {
                int c = Math.Clamp(fixedCol, 0, cols.Count - pd.ColumnSpan), r = 0;
                while (!Fits(r, c, pd.RowSpan, pd.ColumnSpan)) r++;
                (pd.R, pd.C) = (r, c);
                Mark(r, c, pd.RowSpan, pd.ColumnSpan);
                continue;
            }
            while (true)
            {
                if (curC + pd.ColumnSpan > cols.Count) { curC = 0; curR++; }
                if (Fits(curR, curC, pd.RowSpan, pd.ColumnSpan)) break;
                curC++;
            }
            (pd.R, pd.C) = (curR, curC);
            Mark(curR, curC, pd.RowSpan, pd.ColumnSpan);
            curC += pd.ColumnSpan;
        }

        int rowCount = Math.Max(occupied.Count, Children.Count == 0 ? 0 : Children.Max(ch => PD(ch).R + PD(ch).RowSpan));
        rowCount = Math.Max(rowCount, _rows.Count);
        var rows = new List<GridTrack>(_rows);
        while (rows.Count < rowCount) rows.Add(_autoRow);

        // --- column sizes ---
        var colW = new float[cols.Count];
        float colGaps = _columnGap * (cols.Count - 1);
        for (int i = 0; i < cols.Count; i++)
            if (cols[i].Kind == TrackKind.Px) colW[i] = cols[i].Value;

        void GrowAuto(float[] sizes, IReadOnlyList<GridTrack> tracks, int start, int span, float need, float gap)
        {
            float have = gap * (span - 1);
            for (int k = start; k < start + span; k++) have += sizes[k];
            if (need <= have) return;
            var autos = Enumerable.Range(start, span).Where(k => tracks[k].Kind != TrackKind.Px).ToList();
            if (autos.Count == 0) return;
            float add = (need - have) / autos.Count;
            foreach (var k in autos) sizes[k] += add;
        }

        // Single-column items first, then spanning ones.
        foreach (var span1 in new[] { true, false })
            foreach (var child in Children)
            {
                var pd = PD(child);
                if ((pd.ColumnSpan == 1) != span1) continue;
                bool flexOnly = Enumerable.Range(pd.C, pd.ColumnSpan).All(k => cols[k].Kind == TrackKind.Fr) && float.IsFinite(maxW);
                if (flexOnly) continue; // fr tracks take what is left, not what content wants
                if (Enumerable.Range(pd.C, pd.ColumnSpan).All(k => cols[k].Kind == TrackKind.Px)) continue;
                float need = child.MaxIntrinsicWidth(float.PositiveInfinity);
                GrowAuto(colW, cols, pd.C, pd.ColumnSpan, need, _columnGap);
            }

        float frTotal = cols.Where(c => c.Kind == TrackKind.Fr).Sum(c => c.Value);
        bool hasFr = frTotal > 0;
        if (hasFr && float.IsFinite(maxW))
        {
            float used = colGaps;
            for (int i = 0; i < cols.Count; i++) if (cols[i].Kind != TrackKind.Fr) used += colW[i];
            float free = Math.Max(0, maxW - used);
            for (int i = 0; i < cols.Count; i++)
                if (cols[i].Kind == TrackKind.Fr) colW[i] = free * cols[i].Value / frTotal;
        }

        float ColSpanWidth(GridParentData pd)
        {
            float w = _columnGap * (pd.ColumnSpan - 1);
            for (int k = pd.C; k < pd.C + pd.ColumnSpan; k++) w += colW[k];
            return w;
        }

        // --- row sizes ---
        var rowH = new float[rows.Count];
        for (int i = 0; i < rows.Count; i++)
            if (rows[i].Kind == TrackKind.Px) rowH[i] = rows[i].Value;

        float rowGaps = _rowGap * Math.Max(0, rows.Count - 1);
        bool rowsFlex = rows.Any(r => r.Kind == TrackKind.Fr) && float.IsFinite(maxH);
        foreach (var span1 in new[] { true, false })
            foreach (var child in Children)
            {
                var pd = PD(child);
                if ((pd.RowSpan == 1) != span1) continue;
                if (Enumerable.Range(pd.R, pd.RowSpan).All(k => rows[k].Kind == TrackKind.Px)) continue;
                if (rowsFlex && Enumerable.Range(pd.R, pd.RowSpan).All(k => rows[k].Kind == TrackKind.Fr)) continue;
                float w = ColSpanWidth(pd);
                child.Layout(new BoxConstraints(w, w, 0, float.PositiveInfinity));
                GrowAuto(rowH, rows, pd.R, pd.RowSpan, child.Size.Height, _rowGap);
            }

        float rowFr = rows.Where(r => r.Kind == TrackKind.Fr).Sum(r => r.Value);
        if (rowFr > 0 && float.IsFinite(maxH))
        {
            float used = rowGaps;
            for (int i = 0; i < rows.Count; i++) if (rows[i].Kind != TrackKind.Fr) used += rowH[i];
            float free = Math.Max(0, maxH - used);
            for (int i = 0; i < rows.Count; i++)
                if (rows[i].Kind == TrackKind.Fr) rowH[i] = free * rows[i].Value / rowFr;
        }

        float totalW = colW.Sum() + colGaps, totalH = rowH.Sum() + rowGaps;
        Size = Constraints.Constrain(new Size(totalW, totalH));

        // --- final placement ---
        var colX = new float[cols.Count];
        float x = 0;
        for (int i = 0; i < cols.Count; i++) { colX[i] = x; x += colW[i] + _columnGap; }
        var rowY = new float[rows.Count];
        float y = 0;
        for (int i = 0; i < rows.Count; i++) { rowY[i] = y; y += rowH[i] + _rowGap; }

        foreach (var child in Children)
        {
            var pd = PD(child);
            float cw = ColSpanWidth(pd);
            float ch = _rowGap * (pd.RowSpan - 1);
            for (int k = pd.R; k < pd.R + pd.RowSpan; k++) ch += rowH[k];

            if (pd.Alignment is { } align)
            {
                child.Layout(new BoxConstraints(0, cw, 0, ch));
                pd.Offset = new Offset(colX[pd.C], rowY[pd.R]) + align.AlongSize(new Size(cw, ch), child.Size);
            }
            else
            {
                child.Layout(BoxConstraints.Tight(new Size(cw, ch)));
                pd.Offset = new Offset(colX[pd.C], rowY[pd.R]);
            }
        }
    }

    public override void Paint(PaintingContext context, Offset offset)
    {
        foreach (var c in Children) context.PaintChild(c, offset + OffsetOf(c));
    }

    protected override bool HitTestChildren(HitTestResult result, Offset position)
    {
        for (int i = Children.Count - 1; i >= 0; i--)
            if (HitTestChild(Children[i], result, position)) return true;
        return false;
    }
}
